spring.application.name=delivery-kafka-stream
spring.kafka.bootstrap-servers=http://localhost:9092
spring.kafka.streams.application-id=delivery-streams-app
spring.kafka.streams.state-dir=/tmp/kafka-streams
spring.kafka.streams.auto-startup=true

# Disable cache to process messages in real-time
spring.kafka.streams.cache.max.bytes.buffering=0

# Ensure correct exception handling
spring.kafka.streams.default.deserialization.exception.handler=org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

# Schema Registry Configuration
spring.kafka.properties.schema.registry.url=http://localhost:8081
spring.kafka.properties.auto.register.schemas=true

# Kafka Consumer Configuration
spring.kafka.consumer.group-id=delivery-status-consumer-group-1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.system.delivery.schema

# Kafka Streams JSON Configuration
spring.kafka.streams.properties.spring.json.trusted.packages=com.system.delivery.schema

# Kafka Topics
delivery.streams.status.topic=delivery-status-updates
# to be used in case we finish all the metrics
delivery.streams.metrics.store=delivery-metrics-store
delivery.streams.avg.time.store=average-delivery-time-store
delivery.streams.delayed.count.store=delayed-deliveries-store
delivery.streams.delivery.by.status=deliveries-by-status


server.address=0.0.0.0
server.port=8080

#Prometheus & Health Monitoring
management.endpoints.web.exposure.include=prometheus,health,metrics
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.endpoint.health.show-details=always
