spring.application.name=demo
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/postgres
spring.flyway.user=postgres
spring.flyway.password=postgres

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.sql.init.mode=always
spring.sql.init.platform=postgres

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.web=DEBUG

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=3000
# Enable Redis Cache
spring.cache.type=redis
#DEBUG CACHING 
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis=DEBUG

#Security
jwt.secret=/GTs+BV37y8WqhSQYFrd9SrdGAt564waV5eNpsrMHwg=
logging.level.org.springframework.security=DEBUG


#Kafka setup 
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.properties.schema.registry.url=http://localhost:8081
spring.kafka.properties.auto.register.schemas=true

server.port=8888